# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d28e2d67277838d5edd0fac275207f9fd7100a1937c75f71432f17958c96da943be1b45c15305575cbe56d298ecb11d5c0c4ee21277e790fdc6943c653067ab8

test:
  secret_key_base: ad5c1b00038d719eaaf4e23b4d593da51da11c33cfa0781ddf0fd1eefab9d2c6e1f974da2743a80040e382024fff1bd512578364f58839780b343117a9ef6d7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ad5c1b00038d719eaaf4e23b4d593da51da11c33cfa0781ddf0fd1eefab9d2c6e1f974da2743a80040e382024fff1bd512578364f58839780b343117a9ef6d7b
